### ISSUE TITLE
Minor typo to be fixed

### ISSUE THREAD

**Issue by perez987** [chris1111/GateKeeper-Tools#1]
Great app, as always. 
There are 2 occurrences of inseret instead of insert:

`printf -- '%s\n' "Inseret Your Password To Procceed."`

**Comment by chris1111** [comment]
Thanks for the catch @perez987 
Done [commits](https://github.com/chris1111/GateKeeper-Tools/commit/05461b970f2ca45b3f9aa87ce0b9d3eb60ff2555)
